# Docker Compose 配置文件 for Vue.js 前端项目
version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vue-frontend
    ports:
      - "3000:80"  # 映射容器的80端口到主机的3000端口
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 后端服务（可选，根据实际情况配置）
  # backend:
  #   image: your-backend-image:latest
  #   container_name: backend-api
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - DATABASE_URL=jdbc:mysql://db:3306/your_database
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  # 数据库服务（可选）
  # db:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: your_database
  #     MYSQL_USER: your_user
  #     MYSQL_PASSWORD: your_password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   restart: unless-stopped
  #   networks:
  #     - app-network

# 网络配置
networks:
  app-network:
    driver: bridge

# 数据卷配置（如果使用数据库）
# volumes:
#   mysql_data:
#     driver: local